### ISSUE TITLE
allow option to purge

### ISSUE THREAD

**Issue by technovangelist** [IgorVaryvoda/gh-action-sirv#2]
This is fantastic. It adds images that were added to GitHub correctly to where I posted them. The one thing I wished it did was purge/delete images that are no longer in the repository. So maybe that part of the yaml on my repo is:

```
      - uses: sirv/gh-action-sirv@main
        name: Upload to Sirv
        id: Sirv
        with:
          clientId: ${{ secrets.SIRVCLIENTID }}
          clientSecret: ${{ secrets.SIRVCLIENTSECRET}}
          source_dir: 'docs/images'
          output_dir: 'docs'
		  purge: true
```
and purge being true means it gets a listing of all the images there in the repo and any that are not there but are on sirv get deleted from sirv. or maybe there is also a `trash` option that moves those images to a trash folder and purged at the next run of the action at least 7 days later. That should solve the problem of deleting an image that shouldn't be deleted.
